stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk:12-alpine
  script:
    - ./gradlew build
  artifacts:
    paths:
      - ./build/libs/

smoke test:
  stage: test
  image: openjdk:12-alpine
  before_script:
    - apk --no-cache add curl
  script:
    - java -jar ./build/libs/cars-api.jar &
    - sleep 30
    - curl http://localhost:5000/actuator/health | grep "UP"

variables:
  AWS_ACCESS_KEY_ID: AKIAZODMIG3FQL3A4W5B
  AWS_SECRET_ACCESS_KEY: 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
  S3_BUCKET_NAME: carsapi123

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set region us-east-1
    - aws s3 cp build/libs/cars-api.jar s3://$S3_BUCKET_NAME/cars-api.jar